### ISSUE TITLE
Error in  removing user (privacy)

### ISSUE THREAD

**Issue by behoof** [Elearning-HWR-Berlin/moodle-block_social-comments#17]
Error reading database:

0 /home/site/public_html/connect/lib/dml/mysqli_native_moodle_database.php(1186): moodle_database->query_end(false)
#1 /home/site/public_html/connect/privacy/classes/local/request/contextlist.php(71): mysqli_native_moodle_database->get_recordset_sql('\n              ...', Array)
#2 /home/site/public_html/connect/blocks/socialcomments/classes/privacy/provider.php(132): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id\n   ...', Array)
#3 /home/site/public_html/connect/lib/moodlelib.php(7992): block_socialcomments\privacy\provider::get_contexts_for_userid(422)
#4 /home/site/public_html/connect/privacy/classes/manager.php(578): component_class_callback('block_socialcom...', 'get_contexts_fo...', Array)
#5 /home/site/public_html/connect/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('block_socialcom...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#6 /home/site/public_html/connect/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('block_socialcom...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /home/site/public_html/connect/admin/tool/dataprivacy/classes/task/process_data_request_task.php(94): core_privacy\manager->get_contexts_for_userid(422)
#8 /home/site/public_html/connect/lib/cronlib.php(284): tool_dataprivacy\task\process_data_request_task->execute()
#9 /home/site/public_html/connect/lib/cronlib.php(166): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#10 /home/site/public_html/connect/lib/cronlib.php(76): cron_run_adhoc_tasks(1601712902)
#11 /home/site/public_html/connect/admin/cli/cron.php(61): cron_run()
#12 {main}

**Comment by ratondeau** [comment]
What exactly did you do to get this error?

**Comment by behoof** [comment]
In the deletion of user data [within the Data Privacy contect](https://docs.moodle.org/39/en/Data_privacy)

**Comment by ratondeau** [comment]
Ok thanks will have a look into this.

**Comment by ratondeau** [comment]
Hi @behoof 

I tried to reproduce this error but did not manage it so far. Could you specify the exact preconditions and actions you have done to get the error. I guess the specific user also had done some (social comments) posts within several courses.

**Comment by mattgig** [comment]
I have just come across the very same problem in Moodle 3.11.1, every time the cron job runs Moodle sends an error report like the one described above.

As far as I can tell, it startet when a user sent in a data request and I approved it: https://.../moodle/admin/tool/dataprivacy/datarequests.php

In case you need more details, let me know and I will investigate.

**Comment by ratondeau** [comment]
Ok thanks that is at least a point where I can start, thanks. I will have a look into this.
